# Generated by Django 5.0.4 on 2024-04-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restauranet_type',
            field=models.CharField(choices=[('IN', 'Indian'), ('Ch', 'Chinese'), ('IT', 'Italian'), ('GR', 'Greek'), ('FF', 'Fast Food'), ('OT', 'Other')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
